# Docs available at https://github.com/rustyscreeps/cargo-screeps/

default_deploy_mode = "pserver"

[pserver]
username = "your username"
password = "your password"
hostname = "private server hostname"
port = 21025
ssl = false

[mmo]
auth_token = "your screeps.com auth token"

# This is required (except features) due to MMO having an outdated Node.js version.
[mmo.build]
extra_options = ["--features=mmo", "--config", "build.rustflags=['-Ctarget-cpu=mvp']", "-Z", "build-std=std,panic_abort", "-Z", "build-std-features=panic_immediate_abort"]

[ptr]
auth_token = "your screeps.com auth token"
prefix = "ptr"

[ptr.build]
extra_options = ["--features=mmo", "--config", "build.rustflags=['-Ctarget-cpu=mvp']", "-Z", "build-std=std,panic_abort", "-Z", "build-std-features=panic_immediate_abort"]

[copy]
destination = "path to your local code directory from your game client, without branch directory"

[season]
auth_token = "your screeps.com auth token"
prefix = "season"

[season.build]
extra_options = ["--features=my-crate-season-1-feature"]